name: Snake animation

on:
  schedule:
    - cron: "0 0 * * *" # executa diariamente
  workflow_dispatch:     # permite rodar manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}