name: Snake animation

on:
  schedule:
    - cron: "0 0 * * *" # diário
  workflow_dispatch:     # permite rodar manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: github-snake.svg  # <--- ESSENCIAL, define o arquivo de saída

      - name: Commit Snake
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add github-snake.svg
          git commit -m "Update Snake animation" || echo "No changes to commit"
          git push