name: Snake animation

on:
  schedule:
    - cron: "0 0 * * *" # executa diariamente
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snake
        uses: platane/snk@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}